version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"

'''
# To build and run the project using Docker Compose, run the following command in your terminal:
docker-compose up --build
'''